In [ ]:
import tensorflow as tf
print(tf.__version__)

2.8.0


## Creating tensor with `tf.Variable`

In [ ]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [ ]:
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([5, 6])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 6], dtype=int32)>)

In [ ]:
changeable_tensor[0].assign(2)
changeable_tensor


<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([2, 7], dtype=int32)>

## Create a Random Tensors

In [ ]:
#create first matrices
random_matrices_1 = tf.random.Generator.from_seed(25)
random_matrices_1 = random_matrices_1.normal(shape=(3, 3))
random_matrices_1

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.14371012, -0.34646833,  1.1456194 ],
       [-0.416     ,  0.43369916,  1.0241015 ],
       [-0.74785167, -0.59090924, -1.2060374 ]], dtype=float32)>

In [ ]:
#create another matrices
random_matrices_2 = tf.random.Generator.from_seed(20)
random_matrices_2 = random_matrices_2.normal(shape=(3,3))
random_matrices_2

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.88051325, -1.6833194 ,  0.86754173],
       [-0.19625713, -1.322665  , -0.02279496],
       [-0.1383193 ,  0.44207528, -0.7531523 ]], dtype=float32)>

# PERHATIAN!!!
`from_seed` untuk mengatur konsistensi dari matriks tersebut, contoh jika `from_seed` sama, maka matriks akan bernilai sama

In [ ]:
sum_of_random = random_matrices_1 * random_matrices_2

In [ ]:
sum_of_random

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.12653866,  0.5832169 ,  0.99387264],
       [ 0.08164297, -0.5736387 , -0.02334435],
       [ 0.10344232, -0.26122636,  0.90832984]], dtype=float32)>

## Shuffle the order elements of tensor

In [ ]:
#non shuffle matrices
tf.random.set_seed(20)
a_matrices = tf.constant([[10, 11],
                          [5, 6],
                          [12, 1]])

a_shuffled_matrices = tf.random.shuffle(a_matrices)

print(f'Before : \n{a_matrices}\n\nAfter: \n{a_shuffled_matrices}')

Before : 
[[10 11]
 [ 5  6]
 [12  1]]

After: 
[[10 11]
 [12  1]
 [ 5  6]]


## Otherways to make tensors

In [ ]:
#using numpy 
import numpy as np

In [ ]:
numpy_A = np.arange(1, 37, dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36], dtype=int32)

In [ ]:
tf.constant(numpy_A)

<tf.Tensor: shape=(36,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36], dtype=int32)>

### Notes: 
> So the different between numpy and tensor in matrices, numpy can't run on GPU, but tensor can run in GPU

In [ ]:
tf.constant(numpy_A, shape=(3, 3, 4))

<tf.Tensor: shape=(3, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]],

       [[25, 26, 27, 28],
        [29, 30, 31, 32],
        [33, 34, 35, 36]]], dtype=int32)>

## Getting information from tensor

When dealing with tensor you probably want to be aware of the following attributes:

* Shape
* Rank
* Axis or dimension
* Size

In [ ]:
rank_4_tensor = tf.ones(shape=(2, 3, 4, 5))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
print(f'Data type every elements : {rank_4_tensor.dtype}')
print(f'Number of dimensions (rank): {rank_4_tensor.ndim}')
print(f'Shape of tensors: {rank_4_tensor.shape}')
print(f'Elements along the 0 axis: {rank_4_tensor.shape[0]}')
print(f'Elements along the last axis: {rank_4_tensor.shape[-1]}')
print(f'Total of number elements of the tensor: {tf.size(rank_4_tensor)}')
print(f'Total of number elements of the tensor: {tf.size(rank_4_tensor).numpy()}')

Data type every elements : <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensors: (2, 3, 4, 5)
Elements along the 0 axis: 2
Elements along the last axis: 5
Total of number elements of the tensor: 120
Total of number elements of the tensor: 120


In [ ]:
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]]], dtype=float32)>

In [ ]:
rank_3_tensor = rank_4_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 3, 4, 5, 1), dtype=float32, numpy=
array([[[[[1.],
          [1.],
          [1.],
          [1.],
          [1.]],

         [[1.],
          [1.],
          [1.],
          [1.],
          [1.]],

         [[1.],
          [1.],
          [1.],
          [1.],
          [1.]],

         [[1.],
          [1.],
          [1.],
          [1.],
          [1.]]],


        [[[1.],
          [1.],
          [1.],
          [1.],
          [1.]],

         [[1.],
          [1.],
          [1.],
          [1.],
          [1.]],

         [[1.],
          [1.],
          [1.],
          [1.],
          [1.]],

         [[1.],
          [1.],
          [1.],
          [1.],
          [1.]]],


        [[[1.],
          [1.],
          [1.],
          [1.],
          [1.]],

         [[1.],
          [1.],
          [1.],
          [1.],
          [1.]],

         [[1.],
          [1.],
          [1.],
          [1.],
          [1.]],

         [[1.],
          [1.],
     

In [ ]:
rank_3_tensor.shape


TensorShape([2, 3, 4, 5, 1])

In [ ]:
#alternative
tf.expand_dims(rank_4_tensor, axis=-1)

<tf.Tensor: shape=(2, 3, 4, 5, 1), dtype=float32, numpy=
array([[[[[1.],
          [1.],
          [1.],
          [1.],
          [1.]],

         [[1.],
          [1.],
          [1.],
          [1.],
          [1.]],

         [[1.],
          [1.],
          [1.],
          [1.],
          [1.]],

         [[1.],
          [1.],
          [1.],
          [1.],
          [1.]]],


        [[[1.],
          [1.],
          [1.],
          [1.],
          [1.]],

         [[1.],
          [1.],
          [1.],
          [1.],
          [1.]],

         [[1.],
          [1.],
          [1.],
          [1.],
          [1.]],

         [[1.],
          [1.],
          [1.],
          [1.],
          [1.]]],


        [[[1.],
          [1.],
          [1.],
          [1.],
          [1.]],

         [[1.],
          [1.],
          [1.],
          [1.],
          [1.]],

         [[1.],
          [1.],
          [1.],
          [1.],
          [1.]],

         [[1.],
          [1.],
     

In [ ]:
new_tensor = tf.constant([[2, 4],
                         [6, 9]])
new_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 4],
       [6, 9]], dtype=int32)>

In [ ]:
new_t_tensor = new_tensor[..., tf.newaxis]
new_t_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[2],
        [4]],

       [[6],
        [9]]], dtype=int32)>

In [ ]:
tf.expand_dims(new_tensor, axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[2],
        [4]],

       [[6],
        [9]]], dtype=int32)>

### Manipulating tensor

> Basic Operation:  `+`, `-`, `*`, `/`

In [ ]:
#addition
tensor_1 = tf.constant([[10, 5], 
                        [2, 8]])
tensor_add = tensor_1 + 10

In [ ]:
tensor_add

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 15],
       [12, 18]], dtype=int32)>

In [ ]:
#multiplication
tensor_multi = tensor_1 * 10
tensor_multi

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  50],
       [ 20,  80]], dtype=int32)>

In [ ]:
#subtraction
tensor_sub = tensor_1 - 10
tensor_sub

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -5],
       [-8, -2]], dtype=int32)>

In [ ]:
#multiplication in another way (with TF func)
tf.multiply(tensor_1, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  50],
       [ 20,  80]], dtype=int32)>

In [ ]:
#adding in another way (tf func)
tf.add(tensor_1, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 15],
       [12, 18]], dtype=int32)>

## Tensorflow matrix multiplication

You can use `tf.linalg.matmul` for operate this, but you can use only `tf.matmul`

### Differences betwek matrix multiplication using tensor and python :
* In tensor, we can operate row vs column
* When using Python, we just only linear multiply

__Example__ :


In [ ]:
tensor_1, tensor_multi

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  5],
        [ 2,  8]], dtype=int32)>, <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[100,  50],
        [ 20,  80]], dtype=int32)>)

In [ ]:
#tensorflow matrix multiplication
tf.matmul(tensor_multi, tensor_1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1100,  900],
       [ 360,  740]], dtype=int32)>

In [ ]:
#python matrix multiplication 
tensor_multi * tensor_1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1000,  250],
       [  40,  640]], dtype=int32)>

In [ ]:
# create 3x2 matrix
x = tf.constant([[3, 2],
                 [5, 6],
                 [10, 12]])

# create 2x3 matrix
y = tf.constant([[3, 4, 5],
                 [10, 12, 13]])


In [ ]:
# multiply 3x2 x 2x3
multiply_mat = tf.matmul(x, y)
multiply_mat

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 29,  36,  41],
       [ 75,  92, 103],
       [150, 184, 206]], dtype=int32)>

In [ ]:
# multiply 2x3 x 3x2  
l = [0, 1, 4, 9, 16, 20]
multiply_mat2 = tf.matmul(y, x)
multiply_mat2


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 79,  90],
       [220, 248]], dtype=int32)>

In [ ]:
#using tf.reshape
y, tf.reshape(y, shape=(3, 2))

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 3,  4,  5],
        [10, 12, 13]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 3,  4],
        [ 5, 10],
        [12, 13]], dtype=int32)>)

In [ ]:
# we can do transpose
tf.transpose(y)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3, 10],
       [ 4, 12],
       [ 5, 13]], dtype=int32)>

### Dot Product matrix

In [ ]:
matrix_1 = tf.constant([[1, 2],
                        [3, 4],
                        [5, 6]])
matrix_2 = tf.constant([[7, 8],
                        [9, 10],
                        [11, 12]])

In [ ]:
tf.tensordot(tf.transpose(matrix_1), matrix_2, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [ ]:
tf.matmul(tf.transpose(matrix_1), matrix_2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

### Changing the datatypes of a tensor

> It can make more faster and less memory usage 

In [ ]:
numb_1 = tf.constant([5, 6])
numb_1, numb_1.dtype

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 6], dtype=int32)>,
 tf.int32)

In [ ]:
#change int32 to int16 
numb_1_converted = tf.cast(numb_1, dtype=tf.int16)
numb_1_converted, numb_1_converted

(<tf.Tensor: shape=(2,), dtype=int16, numpy=array([5, 6], dtype=int16)>,
 <tf.Tensor: shape=(2,), dtype=int16, numpy=array([5, 6], dtype=int16)>)

In [ ]:
numb_2 = tf.constant([5.1, 6.2])
numb_2, numb_2.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([5.1, 6.2], dtype=float32)>,
 tf.float32)

In [ ]:
#change flaot32 to float16 
numb_2_converted = tf.cast(numb_2, dtype=tf.float16)
numb_2_converted, numb_2_converted

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([5.1, 6.2], dtype=float16)>,
 <tf.Tensor: shape=(2,), dtype=float16, numpy=array([5.1, 6.2], dtype=float16)>)

### Agregating Tensor

Agregating = condensing them from multiple values down to a smaller amount of values

In [ ]:
# get the absolute values
D = tf.constant([-7, -10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [ ]:
# get the avsolute values
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Lets go through the following forms of aggregation:
* Get the maximum
* Get the minimum
* Get the mean of a tensor
* Get the sum of a tensor


In [ ]:
# create a random tensor with values between 0 and 100 of size 50
E = tf.constant(np.random.randint(0, 100, size=50))
E


<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([70, 11, 89, 41, 53, 69, 27, 16,  0,  2, 22, 77, 10, 52, 76, 10,  7,
       81, 32, 50,  8, 69, 41, 52, 38, 18, 52, 30, 11, 60, 34, 93, 96, 92,
       18, 23, 98, 60, 47, 33, 20, 18, 90, 25, 47, 77, 72, 90,  9, 95])>

In [ ]:
tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [ ]:
# find the minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [ ]:
#using numpi
np.min(E)


0

In [ ]:
#find max
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=98>

In [ ]:
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=46>

In [ ]:
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2311>

In [ ]:
# variance
Evar = tf.cast(E, dtype=tf.float32)
tf.math.reduce_variance(Evar)

<tf.Tensor: shape=(), dtype=float32, numpy=894.2916>

In [ ]:
#standar deviation
tf.math.reduce_std(Evar)

<tf.Tensor: shape=(), dtype=float32, numpy=29.904709>

> Note : If you want search an std or variance, you must change the type of data should be `float`

In [ ]:
import tensorflow_probability as tfp

In [ ]:
#variance using tfp
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=894>

### Finding positional Max and Min

In [ ]:
tf.random.set_seed(45)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.48913598, 0.30816448, 0.8261548 , 0.25587916, 0.2993518 ,
       0.2643453 , 0.21094537, 0.22731137, 0.01557994, 0.12873471,
       0.3316598 , 0.42108238, 0.8701608 , 0.65981686, 0.5743673 ,
       0.6854216 , 0.6515837 , 0.19545841, 0.1441735 , 0.9233247 ,
       0.42670476, 0.8457639 , 0.3934058 , 0.9006833 , 0.47969007,
       0.6867969 , 0.67909396, 0.7238083 , 0.7927431 , 0.47818553,
       0.47793758, 0.28856158, 0.69985783, 0.5915674 , 0.01672316,
       0.49891758, 0.38331974, 0.6024455 , 0.60487247, 0.51338553,
       0.21195805, 0.507064  , 0.27594423, 0.34573162, 0.01471639,
       0.47635663, 0.8088087 , 0.08854103, 0.77666366, 0.00165653],
      dtype=float32)>

In [ ]:
#find the positional maximum
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=19>

In [ ]:
#index on our largest value position
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9233247>

In [ ]:
# find the max value of F

tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9233247>

In [ ]:
#check equality
assert F[tf.argmax(F)] == tf.reduce_max(F)

In [ ]:
#find index minimum
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=49>

In [ ]:
#find the value of index
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.0016565323>

### Squeezing a tensor (removing all single dimensions)

In [ ]:
tf.random.set_seed(50)
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1, 1, 1, 1, 50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.94196117, 0.1697309 , 0.5064962 , 0.27598453, 0.899318  ,
           0.4486513 , 0.43584716, 0.71771336, 0.85751176, 0.12559032,
           0.0875535 , 0.85261035, 0.17349517, 0.31913245, 0.4845121 ,
           0.5540675 , 0.6620537 , 0.20845115, 0.43225408, 0.9061552 ,
           0.52628434, 0.30039036, 0.5774927 , 0.5814352 , 0.7920803 ,
           0.396855  , 0.02649951, 0.43159127, 0.11073196, 0.5804652 ,
           0.83437836, 0.17531359, 0.5109179 , 0.91586626, 0.21497321,
           0.41104853, 0.7946409 , 0.30716085, 0.3172475 , 0.15829349,
           0.5417241 , 0.49205697, 0.19820452, 0.25472498, 0.2333138 ,
           0.2071842 , 0.5443722 , 0.01052618, 0.57121956, 0.33880603]]]]],
      dtype=float32)>

In [ ]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [ ]:
G_squeezed = tf.squeeze(G)
G_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.94196117, 0.1697309 , 0.5064962 , 0.27598453, 0.899318  ,
       0.4486513 , 0.43584716, 0.71771336, 0.85751176, 0.12559032,
       0.0875535 , 0.85261035, 0.17349517, 0.31913245, 0.4845121 ,
       0.5540675 , 0.6620537 , 0.20845115, 0.43225408, 0.9061552 ,
       0.52628434, 0.30039036, 0.5774927 , 0.5814352 , 0.7920803 ,
       0.396855  , 0.02649951, 0.43159127, 0.11073196, 0.5804652 ,
       0.83437836, 0.17531359, 0.5109179 , 0.91586626, 0.21497321,
       0.41104853, 0.7946409 , 0.30716085, 0.3172475 , 0.15829349,
       0.5417241 , 0.49205697, 0.19820452, 0.25472498, 0.2333138 ,
       0.2071842 , 0.5443722 , 0.01052618, 0.57121956, 0.33880603],
      dtype=float32)>